// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: pkg/protocol/pingve.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PingveService_Connect_FullMethodName = "/protocol.PingveService/Connect"
)

// PingveServiceClient is the client API for PingveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingveServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMsg, ServerMsg], error)
}

type pingveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPingveServiceClient(cc grpc.ClientConnInterface) PingveServiceClient {
	return &pingveServiceClient{cc}
}

func (c *pingveServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMsg, ServerMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PingveService_ServiceDesc.Streams[0], PingveService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMsg, ServerMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PingveService_ConnectClient = grpc.BidiStreamingClient[AgentMsg, ServerMsg]

// PingveServiceServer is the server API for PingveService service.
// All implementations must embed UnimplementedPingveServiceServer
// for forward compatibility.
type PingveServiceServer interface {
	Connect(grpc.BidiStreamingServer[AgentMsg, ServerMsg]) error
	mustEmbedUnimplementedPingveServiceServer()
}

// UnimplementedPingveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPingveServiceServer struct{}

func (UnimplementedPingveServiceServer) Connect(grpc.BidiStreamingServer[AgentMsg, ServerMsg]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedPingveServiceServer) mustEmbedUnimplementedPingveServiceServer() {}
func (UnimplementedPingveServiceServer) testEmbeddedByValue()                       {}

// UnsafePingveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingveServiceServer will
// result in compilation errors.
type UnsafePingveServiceServer interface {
	mustEmbedUnimplementedPingveServiceServer()
}

func RegisterPingveServiceServer(s grpc.ServiceRegistrar, srv PingveServiceServer) {
	// If the following call panics, it indicates UnimplementedPingveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PingveService_ServiceDesc, srv)
}

func _PingveService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PingveServiceServer).Connect(&grpc.GenericServerStream[AgentMsg, ServerMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PingveService_ConnectServer = grpc.BidiStreamingServer[AgentMsg, ServerMsg]

// PingveService_ServiceDesc is the grpc.ServiceDesc for PingveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PingveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.PingveService",
	HandlerType: (*PingveServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _PingveService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/protocol/pingve.proto",
}
