// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/protocol/pingve.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMsg_Auth
	//	*AgentMsg_Heartbeat
	//	*AgentMsg_PingResult
	//	*AgentMsg_MtrResult
	Payload       isAgentMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMsg) Reset() {
	*x = AgentMsg{}
	mi := &file_pkg_protocol_pingve_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMsg) ProtoMessage() {}

func (x *AgentMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_pingve_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMsg.ProtoReflect.Descriptor instead.
func (*AgentMsg) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_pingve_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMsg) GetPayload() isAgentMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMsg) GetAuth() *AuthRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMsg_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *AgentMsg) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentMsg_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMsg) GetPingResult() *PingResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMsg_PingResult); ok {
			return x.PingResult
		}
	}
	return nil
}

func (x *AgentMsg) GetMtrResult() *MTRResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentMsg_MtrResult); ok {
			return x.MtrResult
		}
	}
	return nil
}

type isAgentMsg_Payload interface {
	isAgentMsg_Payload()
}

type AgentMsg_Auth struct {
	Auth *AuthRequest `protobuf:"bytes,1,opt,name=auth,proto3,oneof"`
}

type AgentMsg_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMsg_PingResult struct {
	PingResult *PingResult `protobuf:"bytes,3,opt,name=ping_result,json=pingResult,proto3,oneof"`
}

type AgentMsg_MtrResult struct {
	MtrResult *MTRResult `protobuf:"bytes,4,opt,name=mtr_result,json=mtrResult,proto3,oneof"`
}

func (*AgentMsg_Auth) isAgentMsg_Payload() {}

func (*AgentMsg_Heartbeat) isAgentMsg_Payload() {}

func (*AgentMsg_PingResult) isAgentMsg_Payload() {}

func (*AgentMsg_MtrResult) isAgentMsg_Payload() {}

type ServerMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMsg_Auth
	//	*ServerMsg_PingTask
	//	*ServerMsg_MtrTask
	Payload       isServerMsg_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMsg) Reset() {
	*x = ServerMsg{}
	mi := &file_pkg_protocol_pingve_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMsg) ProtoMessage() {}

func (x *ServerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_pingve_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMsg.ProtoReflect.Descriptor instead.
func (*ServerMsg) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_pingve_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMsg) GetPayload() isServerMsg_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMsg) GetAuth() *AuthResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMsg_Auth); ok {
			return x.Auth
		}
	}
	return nil
}

func (x *ServerMsg) GetPingTask() *PingTask {
	if x != nil {
		if x, ok := x.Payload.(*ServerMsg_PingTask); ok {
			return x.PingTask
		}
	}
	return nil
}

func (x *ServerMsg) GetMtrTask() *MTRTask {
	if x != nil {
		if x, ok := x.Payload.(*ServerMsg_MtrTask); ok {
			return x.MtrTask
		}
	}
	return nil
}

type isServerMsg_Payload interface {
	isServerMsg_Payload()
}

type ServerMsg_Auth struct {
	Auth *AuthResponse `protobuf:"bytes,1,opt,name=auth,proto3,oneof"`
}

type ServerMsg_PingTask struct {
	PingTask *PingTask `protobuf:"bytes,2,opt,name=ping_task,json=pingTask,proto3,oneof"`
}

type ServerMsg_MtrTask struct {
	MtrTask *MTRTask `protobuf:"bytes,3,opt,name=mtr_task,json=mtrTask,proto3,oneof"`
}

func (*ServerMsg_Auth) isServerMsg_Payload() {}

func (*ServerMsg_PingTask) isServerMsg_Payload() {}

func (*ServerMsg_MtrTask) isServerMsg_Payload() {}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_pkg_protocol_pingve_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_pingve_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_pingve_proto_rawDescGZIP(), []int{2}
}

func (x *AuthRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AuthRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_pkg_protocol_pingve_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_pingve_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_pingve_proto_rawDescGZIP(), []int{3}
}

func (x *AuthResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AuthResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Uptime        float64                `protobuf:"fixed64,2,opt,name=uptime,proto3" json:"uptime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_pkg_protocol_pingve_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_pingve_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_pingve_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Heartbeat) GetUptime() float64 {
	if x != nil {
		return x.Uptime
	}
	return 0
}

type PingTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingTask) Reset() {
	*x = PingTask{}
	mi := &file_pkg_protocol_pingve_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingTask) ProtoMessage() {}

func (x *PingTask) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_pingve_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingTask.ProtoReflect.Descriptor instead.
func (*PingTask) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_pingve_proto_rawDescGZIP(), []int{5}
}

func (x *PingTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PingTask) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PingTask) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Sent          int32                  `protobuf:"varint,3,opt,name=sent,proto3" json:"sent,omitempty"`
	Lost          int32                  `protobuf:"varint,4,opt,name=lost,proto3" json:"lost,omitempty"`
	MinRtt        float64                `protobuf:"fixed64,5,opt,name=min_rtt,json=minRtt,proto3" json:"min_rtt,omitempty"`
	MaxRtt        float64                `protobuf:"fixed64,6,opt,name=max_rtt,json=maxRtt,proto3" json:"max_rtt,omitempty"`
	AvgRtt        float64                `protobuf:"fixed64,7,opt,name=avg_rtt,json=avgRtt,proto3" json:"avg_rtt,omitempty"`
	StdDev        float64                `protobuf:"fixed64,8,opt,name=std_dev,json=stdDev,proto3" json:"std_dev,omitempty"`
	Rtts          []float64              `protobuf:"fixed64,9,rep,packed,name=rtts,proto3" json:"rtts,omitempty"`
	Seq           int32                  `protobuf:"varint,10,opt,name=seq,proto3" json:"seq,omitempty"`
	Ttl           int32                  `protobuf:"varint,11,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Time          float64                `protobuf:"fixed64,12,opt,name=time,proto3" json:"time,omitempty"`
	IsFinal       bool                   `protobuf:"varint,13,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResult) Reset() {
	*x = PingResult{}
	mi := &file_pkg_protocol_pingve_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResult) ProtoMessage() {}

func (x *PingResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_pingve_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResult.ProtoReflect.Descriptor instead.
func (*PingResult) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_pingve_proto_rawDescGZIP(), []int{6}
}

func (x *PingResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PingResult) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PingResult) GetSent() int32 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *PingResult) GetLost() int32 {
	if x != nil {
		return x.Lost
	}
	return 0
}

func (x *PingResult) GetMinRtt() float64 {
	if x != nil {
		return x.MinRtt
	}
	return 0
}

func (x *PingResult) GetMaxRtt() float64 {
	if x != nil {
		return x.MaxRtt
	}
	return 0
}

func (x *PingResult) GetAvgRtt() float64 {
	if x != nil {
		return x.AvgRtt
	}
	return 0
}

func (x *PingResult) GetStdDev() float64 {
	if x != nil {
		return x.StdDev
	}
	return 0
}

func (x *PingResult) GetRtts() []float64 {
	if x != nil {
		return x.Rtts
	}
	return nil
}

func (x *PingResult) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *PingResult) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *PingResult) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *PingResult) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type MTRTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MTRTask) Reset() {
	*x = MTRTask{}
	mi := &file_pkg_protocol_pingve_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MTRTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTRTask) ProtoMessage() {}

func (x *MTRTask) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_pingve_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTRTask.ProtoReflect.Descriptor instead.
func (*MTRTask) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_pingve_proto_rawDescGZIP(), []int{7}
}

func (x *MTRTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MTRTask) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MTRTask) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MTRHop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hop           int32                  `protobuf:"varint,1,opt,name=hop,proto3" json:"hop,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Ptr           string                 `protobuf:"bytes,3,opt,name=ptr,proto3" json:"ptr,omitempty"`
	AsName        string                 `protobuf:"bytes,4,opt,name=as_name,json=asName,proto3" json:"as_name,omitempty"`
	Loss          float64                `protobuf:"fixed64,5,opt,name=loss,proto3" json:"loss,omitempty"`
	Sent          int32                  `protobuf:"varint,6,opt,name=sent,proto3" json:"sent,omitempty"`
	Last          float64                `protobuf:"fixed64,7,opt,name=last,proto3" json:"last,omitempty"`
	Avg           float64                `protobuf:"fixed64,8,opt,name=avg,proto3" json:"avg,omitempty"`
	Best          float64                `protobuf:"fixed64,9,opt,name=best,proto3" json:"best,omitempty"`
	Worst         float64                `protobuf:"fixed64,10,opt,name=worst,proto3" json:"worst,omitempty"`
	Stdev         float64                `protobuf:"fixed64,11,opt,name=stdev,proto3" json:"stdev,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MTRHop) Reset() {
	*x = MTRHop{}
	mi := &file_pkg_protocol_pingve_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MTRHop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTRHop) ProtoMessage() {}

func (x *MTRHop) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_pingve_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTRHop.ProtoReflect.Descriptor instead.
func (*MTRHop) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_pingve_proto_rawDescGZIP(), []int{8}
}

func (x *MTRHop) GetHop() int32 {
	if x != nil {
		return x.Hop
	}
	return 0
}

func (x *MTRHop) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *MTRHop) GetPtr() string {
	if x != nil {
		return x.Ptr
	}
	return ""
}

func (x *MTRHop) GetAsName() string {
	if x != nil {
		return x.AsName
	}
	return ""
}

func (x *MTRHop) GetLoss() float64 {
	if x != nil {
		return x.Loss
	}
	return 0
}

func (x *MTRHop) GetSent() int32 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *MTRHop) GetLast() float64 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *MTRHop) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *MTRHop) GetBest() float64 {
	if x != nil {
		return x.Best
	}
	return 0
}

func (x *MTRHop) GetWorst() float64 {
	if x != nil {
		return x.Worst
	}
	return 0
}

func (x *MTRHop) GetStdev() float64 {
	if x != nil {
		return x.Stdev
	}
	return 0
}

type MTRResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	RawOutput     string                 `protobuf:"bytes,3,opt,name=raw_output,json=rawOutput,proto3" json:"raw_output,omitempty"`
	Hop           *MTRHop                `protobuf:"bytes,4,opt,name=hop,proto3" json:"hop,omitempty"`
	IsFinal       bool                   `protobuf:"varint,5,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MTRResult) Reset() {
	*x = MTRResult{}
	mi := &file_pkg_protocol_pingve_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MTRResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MTRResult) ProtoMessage() {}

func (x *MTRResult) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_pingve_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MTRResult.ProtoReflect.Descriptor instead.
func (*MTRResult) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_pingve_proto_rawDescGZIP(), []int{9}
}

func (x *MTRResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MTRResult) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MTRResult) GetRawOutput() string {
	if x != nil {
		return x.RawOutput
	}
	return ""
}

func (x *MTRResult) GetHop() *MTRHop {
	if x != nil {
		return x.Hop
	}
	return nil
}

func (x *MTRResult) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

var File_pkg_protocol_pingve_proto protoreflect.FileDescriptor

const file_pkg_protocol_pingve_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/protocol/pingve.proto\x12\bprotocol\"\xe6\x01\n" +
	"\bAgentMsg\x12+\n" +
	"\x04auth\x18\x01 \x01(\v2\x15.protocol.AuthRequestH\x00R\x04auth\x123\n" +
	"\theartbeat\x18\x02 \x01(\v2\x13.protocol.HeartbeatH\x00R\theartbeat\x127\n" +
	"\vping_result\x18\x03 \x01(\v2\x14.protocol.PingResultH\x00R\n" +
	"pingResult\x124\n" +
	"\n" +
	"mtr_result\x18\x04 \x01(\v2\x13.protocol.MTRResultH\x00R\tmtrResultB\t\n" +
	"\apayload\"\xa7\x01\n" +
	"\tServerMsg\x12,\n" +
	"\x04auth\x18\x01 \x01(\v2\x16.protocol.AuthResponseH\x00R\x04auth\x121\n" +
	"\tping_task\x18\x02 \x01(\v2\x12.protocol.PingTaskH\x00R\bpingTask\x12.\n" +
	"\bmtr_task\x18\x03 \x01(\v2\x11.protocol.MTRTaskH\x00R\amtrTaskB\t\n" +
	"\apayload\"Y\n" +
	"\vAuthRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"M\n" +
	"\fAuthResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"A\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06uptime\x18\x02 \x01(\x01R\x06uptime\"H\n" +
	"\bPingTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xb0\x02\n" +
	"\n" +
	"PingResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04sent\x18\x03 \x01(\x05R\x04sent\x12\x12\n" +
	"\x04lost\x18\x04 \x01(\x05R\x04lost\x12\x17\n" +
	"\amin_rtt\x18\x05 \x01(\x01R\x06minRtt\x12\x17\n" +
	"\amax_rtt\x18\x06 \x01(\x01R\x06maxRtt\x12\x17\n" +
	"\aavg_rtt\x18\a \x01(\x01R\x06avgRtt\x12\x17\n" +
	"\astd_dev\x18\b \x01(\x01R\x06stdDev\x12\x12\n" +
	"\x04rtts\x18\t \x03(\x01R\x04rtts\x12\x10\n" +
	"\x03seq\x18\n" +
	" \x01(\x05R\x03seq\x12\x10\n" +
	"\x03ttl\x18\v \x01(\x05R\x03ttl\x12\x12\n" +
	"\x04time\x18\f \x01(\x01R\x04time\x12\x19\n" +
	"\bis_final\x18\r \x01(\bR\aisFinal\"G\n" +
	"\aMTRTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xe3\x01\n" +
	"\x06MTRHop\x12\x10\n" +
	"\x03hop\x18\x01 \x01(\x05R\x03hop\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x10\n" +
	"\x03ptr\x18\x03 \x01(\tR\x03ptr\x12\x17\n" +
	"\aas_name\x18\x04 \x01(\tR\x06asName\x12\x12\n" +
	"\x04loss\x18\x05 \x01(\x01R\x04loss\x12\x12\n" +
	"\x04sent\x18\x06 \x01(\x05R\x04sent\x12\x12\n" +
	"\x04last\x18\a \x01(\x01R\x04last\x12\x10\n" +
	"\x03avg\x18\b \x01(\x01R\x03avg\x12\x12\n" +
	"\x04best\x18\t \x01(\x01R\x04best\x12\x14\n" +
	"\x05worst\x18\n" +
	" \x01(\x01R\x05worst\x12\x14\n" +
	"\x05stdev\x18\v \x01(\x01R\x05stdev\"\x9a\x01\n" +
	"\tMTRResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1d\n" +
	"\n" +
	"raw_output\x18\x03 \x01(\tR\trawOutput\x12\"\n" +
	"\x03hop\x18\x04 \x01(\v2\x10.protocol.MTRHopR\x03hop\x12\x19\n" +
	"\bis_final\x18\x05 \x01(\bR\aisFinal2G\n" +
	"\rPingveService\x126\n" +
	"\aConnect\x12\x12.protocol.AgentMsg\x1a\x13.protocol.ServerMsg(\x010\x01BBZ@github.com/awandataindonesia/cekping-agent/pkg/protocol;protocolb\x06proto3"

var (
	file_pkg_protocol_pingve_proto_rawDescOnce sync.Once
	file_pkg_protocol_pingve_proto_rawDescData []byte
)

func file_pkg_protocol_pingve_proto_rawDescGZIP() []byte {
	file_pkg_protocol_pingve_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_pingve_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_protocol_pingve_proto_rawDesc), len(file_pkg_protocol_pingve_proto_rawDesc)))
	})
	return file_pkg_protocol_pingve_proto_rawDescData
}

var file_pkg_protocol_pingve_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_protocol_pingve_proto_goTypes = []any{
	(*AgentMsg)(nil),     // 0: protocol.AgentMsg
	(*ServerMsg)(nil),    // 1: protocol.ServerMsg
	(*AuthRequest)(nil),  // 2: protocol.AuthRequest
	(*AuthResponse)(nil), // 3: protocol.AuthResponse
	(*Heartbeat)(nil),    // 4: protocol.Heartbeat
	(*PingTask)(nil),     // 5: protocol.PingTask
	(*PingResult)(nil),   // 6: protocol.PingResult
	(*MTRTask)(nil),      // 7: protocol.MTRTask
	(*MTRHop)(nil),       // 8: protocol.MTRHop
	(*MTRResult)(nil),    // 9: protocol.MTRResult
}
var file_pkg_protocol_pingve_proto_depIdxs = []int32{
	2, // 0: protocol.AgentMsg.auth:type_name -> protocol.AuthRequest
	4, // 1: protocol.AgentMsg.heartbeat:type_name -> protocol.Heartbeat
	6, // 2: protocol.AgentMsg.ping_result:type_name -> protocol.PingResult
	9, // 3: protocol.AgentMsg.mtr_result:type_name -> protocol.MTRResult
	3, // 4: protocol.ServerMsg.auth:type_name -> protocol.AuthResponse
	5, // 5: protocol.ServerMsg.ping_task:type_name -> protocol.PingTask
	7, // 6: protocol.ServerMsg.mtr_task:type_name -> protocol.MTRTask
	8, // 7: protocol.MTRResult.hop:type_name -> protocol.MTRHop
	0, // 8: protocol.PingveService.Connect:input_type -> protocol.AgentMsg
	1, // 9: protocol.PingveService.Connect:output_type -> protocol.ServerMsg
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pkg_protocol_pingve_proto_init() }
func file_pkg_protocol_pingve_proto_init() {
	if File_pkg_protocol_pingve_proto != nil {
		return
	}
	file_pkg_protocol_pingve_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMsg_Auth)(nil),
		(*AgentMsg_Heartbeat)(nil),
		(*AgentMsg_PingResult)(nil),
		(*AgentMsg_MtrResult)(nil),
	}
	file_pkg_protocol_pingve_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMsg_Auth)(nil),
		(*ServerMsg_PingTask)(nil),
		(*ServerMsg_MtrTask)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_protocol_pingve_proto_rawDesc), len(file_pkg_protocol_pingve_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_protocol_pingve_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_pingve_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_pingve_proto_msgTypes,
	}.Build()
	File_pkg_protocol_pingve_proto = out.File
	file_pkg_protocol_pingve_proto_goTypes = nil
	file_pkg_protocol_pingve_proto_depIdxs = nil
}
